[build]
  command = "npm run build"
  functions = "functions"
  publish = "."
  environment = { NODE_VERSION = "18" }

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["sharp"]

[dev]
  command = "npm start"
  port = 8888